services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - path: .env
        required: true
    volumes:
      - ./config:/config
      - /home/Data:/home/Data # optional
    # ports:
    #   - 8989:8989
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true
