# https://github.com/maybe-finance/maybe/blob/main/docs/hosting/docker.md

services:
  web:
    image: ghcr.io/maybe-finance/maybe:latest
    container_name: maybe
    volumes:
      - app-storage:/rails/storage
    # ports:
    #   - 3000:3000
    restart: unless-stopped
    env_file:
      - path: ../.env
        required: true
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - homelab

  worker:
    image: ghcr.io/maybe-finance/maybe:latest
    command: bundle exec sidekiq
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - path: ../.env
        required: true
    networks:
      - homelab

  redis:
    image: redis:latest
    # ports:
    #   - 6379:6379
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - homelab

volumes:
  app-storage:
  redis-data:

networks:
  homelab:
    external: true
