services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxmanager
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - homelab

networks:
  homelab:
    external: true
