services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    env_file:
      - path: .env
        required: true
    volumes:
      - ./config:/config
      - /home/Data:/home/Data/ # optional
    # ports:
    #   - 8787:8787
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true
