services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Paramaribo
    volumes:
      - ./config:/config
      - /home/Data:/home/Data/ # optional
    # ports:
    #   - 8787:8787
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true
