services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    # ports:
    #   - 5678:5678
    env_file:
      - path: ../.env
        required: true
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER
      - DB_POSTGRESDB_PASSWORD
      - GENERIC_TIMEZONE
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - homelab

networks:
  homelab:
    external: true

volumes:
  n8n_data:
