services:
  pihole:
    image: pihole/pihole
    container_name: pihole
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    # ports:
      # DNS ports
      # - "53:53/tcp"
      # - "53:53/udp"
      # Default HTTP Port
      # - "8810:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      # - "443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      # - "67:67/udp"
    network_mode: "host"
    env_file:
      - path: .env
        required: true
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - ./config/etc/pihole:/etc/pihole
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards
      # - ./config/etc/dnsmasq.d:/etc/dnsmasq.d
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
      - NET_BIND_SERVICE
    restart: unless-stopped
    # networks:
    #   - homelab

# networks:
#   homelab:
#     external: true
