services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - path: .env
        required: true
    volumes:
      - ./config:/config
      - /home/Data:/home/Data # optional
    # ports:
    #   - 7878:7878
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true
