services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Paramaribo
    volumes:
      - ./config:/config
      - /home/Data/Downloads:/home/Data/Downloads #optional
      - /home/Data/Films:/home/Data/Films #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true
