services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - path: .env
    # ports:
    #   - 8888:80

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    env_file:
      - path: .env
        required: true

