services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - path: .env
        required: true
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - homelab
    # ports:
    #   - 8888:80

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    env_file:
      - path: .env
        required: true
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - homelab

networks:
  homelab:
    external: true

volumes:
  postgres-data:
