services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - ./configs:/app/data/configs
      - ./data:/data
      - ./icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # ports:
    #   - '7575:7575'
    networks:
      - homelab

networks:
  homelab:
    external: true
