services:
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    restart: unless-stopped
    volumes:
      - ./appdata:/appdata
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
    env_file:
      - path: .env
    # ports:
    #   - 7575:7575
    networks:
      - homelab

networks:
  homelab:
    external: true
