services:
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    restart: unless-stopped
    volumes:
      - ./homarr/appdata:/appdata
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
    environment:
      - .env
    # ports:
    #   - '7575:7575'
    networks:
      - homelab

networks:
  homelab:
    external: true
