services:
  disk-monitor:
    build:
      context: ./disk-monitor
    container_name: disk-monitor
    restart: unless-stopped
    env_file:
      - path: .env
        required: true
    volumes:
      - ./scripts:/scripts:ro
      - /:/host:ro
    privileged: true  # required for dmesg access
    networks:
      - homelab

networks:
  homelab:
    external: true
