services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: /home/Data  # TODO: change it
        target: /myMedia
    # Optional - alternative address used for autodiscovery
    env_file:
      - path: ../.env
        required: true
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # ports:
    #   - 8096:8096
    networks:
      - homelab

networks:
  homelab:
    external: true
