services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    env_file:
      - path: .env
        required: true
    volumes:
      - ./config:/config
      - /home/Data/Downloads:/home/Data/Downloads
    # ports:
    #   - 443:443
    #   - 6881:6881
    #   - 6881:6881/udp
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true
