services:
  dash:
    image: mauricenino/dashdot:latest
    container_name: dash
    restart: unless-stopped
    privileged: true
    environment:
      - DASHDOT_PAGE_TITLE=Dash | HomeLab
      - DASHDOT_SHOW_DASH_VERSION=icon_hover
      - DASHDOT_ALWAYS_SHOW_PERCENTAGES=true
      - DASHDOT_CUSTOM_HOST=dash.ragnarokreinier.network
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_SHOW_HOST=true
      - DASHDOT_ACCEPT_OOKLA_EULA=true
      - DASHDOT_USER_NETWORK_INTERFACE=wlp2s0
    # ports:
    #   - 3001:3001
    volumes:
      - /:/mnt/host:ro
    networks:
      - homelab

networks:
  homelab:
    external: true
